---
vars:
  backup_lock_created: '/tmp/replica_lock_created'

- name: MySQL Physical Master Setup
  hosts: all
  tasks:
    - stat:
       path: "{{ backup_lock_created }}"
      register: executing

    - name: Creating MySQL Physical Master execution file
      file:
        path: "{{ backup_lock_created }}"
        state: touch
      when: executing.stat.islnk is not defined

     - name: Transfering MySQL Physical Master script
       copy: src=mysql_physical_replica/master_new_db_node.sh dest=/tmp mode=0777

     - name: Executing MySQL Physical Master script
       command: "sh /tmp/master_new_db_node.sh {{ replica_address }} {{ replica_port }}"
       register: cmd_physical
       async: 86400
       poll: 0
       when: executing.stat.islnk is not defined
     - debug: msg="{{ cmd_physical.stdout_lines|replace('\\t',' ') }}"
     - debug: msg="{{ cmd_physical.stderr_lines|replace('\\t',' ') }}"

     - name: Wait until the lock file is removed
       wait_for:
          path: "{{ backup_lock_created }}"
          state: absent
          delay: 60
          timeout: 86400
       when: executing.stat.islnk is not defined

     - name: Ansible delete - MySQL Physical Master script
       file:
         path: /tmp/master_new_db_node.sh
         state: absent
       when: executing.stat.islnk is not defined
