---
- name: MySQL Physical Replica Setup - Master Server
  gather_facts: false
  hosts: all
  tasks:
  - block:
     - stat:
        path: "{{ lock_created }}"
       register: executing

     - name: Creating MySQL Physical Replica execution file
       file:
         path: "{{ lock_created }}"
         state: touch
       when: executing.stat.islnk is not defined

     - name: Transfering MySQL Physical Replica script - Master Server
       copy: src=mysql_physical_replica/master_new_db_node.sh dest=/tmp mode=0777

     - name: Executing MySQL Physical Replica script - Master Server
       command: "sh /tmp/master_new_db_node.sh {{ replica_address }} {{ replica_port }}"
       register: cmd_physical
       when: executing.stat.islnk is not defined
     - debug: msg="{{ cmd_physical.stdout_lines|replace('\\t',' ') }}"
     - debug: msg="{{ cmd_physical.stderr_lines|replace('\\t',' ') }}"

     - name: Wait until the lock file is removed
       wait_for:
          path: "{{ lock_created }}"
          state: absent
          delay: 60
          timeout: 86400
       when: executing.stat.islnk is not defined

     - name: Removing - MySQL Physical Replica script - Master Server
       file:
         path: /tmp/master_new_db_node.sh
         state: absent
       when: executing.stat.islnk is not defined
